### ISSUE TITLE
Roll and refresh issues

### ISSUE THREAD

**Issue by celtichawk** [AresMUSH/ares-fate-plugin#1]
I've run into this on a fresh install on a live game with the plugin.

Trying to roll vs unnamed characters as explained in help roll gives me this:

System: Sorry! The code lost its mind while executing a command.  Not your fault.
Please send this error information to the admins and tell them what you were doing at the time:
Description: "roll yeet vs bob/good"
Error: "undefined method `name' for nil:NilClass"

Where Bob is the nameless NPC in a test scene

And doing fate/refresh as described in help manage fate gives this:

System: Sorry! The code lost its mind while executing a command.  Not your fault.
Please send this error information to the admins and tell them what you were doing at the time:
Description: "fate/refresh"
Error: "undefined local variable or method `fate_refresh' for AresMUSH::Fate:Module
Did you mean?  update_refresh"

Is there anything I can do on my end about this or is it a case of waiting on a fix and reinstall the plugin?

**Comment by lynnfaraday** [comment]
That's not you, it's just a bug.  Will fix in the next patch thanks.
FYI - I don't really use GitHub issues for tracking anything.  You can report issues on discord or forums.
